name: Survival
main: com.lxgshadow.survival.Main
version: 1.0.0 - SNAPSHOT
author: lxgshadow
depend:
commands:
  tpa:
  suicide:
  team:
  home:
  sethome:
  delhome:
  homelist:
  broadcast:
  vanish:
  unvanish:
  ec:
    aliases: [enderchest]
