name: Survival
main: com.lxgshadow.survival.Main
version: 1.0.0 - SNAPSHOT
api-version: 1.14
author: lxgshadow
depend:
commands:
  tpa:
  suicide:
  team:
  home:
  sethome:
  delhome:
  homelist:
  broadcast:
  vanish:
  unvanish:
  ec:
    aliases: [enderchest]
  forcemsg:
  openinv:
  hat:
  whereami:
    aliases: [wai]

